- name: Install and enable firewalld
  ansible.builtin.dnf:
    name: firewalld
    state: present

- name: Start and enable firewalld
  ansible.builtin.systemd:
    name: firewalld
    state: started
    enabled: true

- name: Add trusted sources to firewalld trusted zone
  ansible.posix.firewalld:
    source: "{{ item }}"
    zone: trusted
    immediate: true
    permanent: true
    state: enabled
  loop:
    - 192.168.5.0/24
    - 10.42.0.0/16
    - 10.43.0.0/16

- name: Permit ssh Service via firewalld
  ansible.posix.firewalld:
    service: ssh
    zone: public
    immediate: true
    permanent: true
    state: enabled

- name: Permit k3s API Server Port (6443) via firewalld
  ansible.posix.firewalld:
    port: 6443/tcp
    zone: public
    immediate: true
    permanent: true
    state: enabled

- name: Permit NodePort Services Ports (30000-32767) via firewalld
  ansible.posix.firewalld:
    port: 30000-32767/tcp
    zone: public
    immediate: true
    permanent: true
    state: enabled

- name: Permit NodePort Port 80 for traefik via firewalld
  ansible.posix.firewalld:
    port: 80/tcp
    zone: public
    immediate: true
    permanent: true
    state: enabled

- name: Permit NodePort 443 for traefik vie firewalld
  ansible.posix.firewalld:
    port: 443/tcp
    zone: public
    immediate: true
    permanent: true
    state: enabled