all:
  children:
    truenas_hosts:
      hosts:
        truenas:
          ansible_host: 192.168.10.25
    proxmox:
      hosts:
        nova:
          ansible_host: 192.168.10.22
        helix:
          ansible_host: 192.168.10.20
        vega:
          ansible_host: 192.168.10.21
    netboot:
      hosts:
        netboot:
          ansible_host: 192.168.10.156
    mediastack:
      hosts:
        mediastack:
          ansible_host: 192.168.30.62
    dev:
      hosts:
        dev:
          ansible_host: 192.168.10.50
    nextcloud:
      hosts:
        nextcloud:
          ansible_host: 192.168.30.82
    dns:
      hosts:
        pi01:
          ansible_host: 192.168.1.2
        pi02:
          ansible_host: 192.168.1.3
