all:
  children:
    truenas:
      hosts:
        truenas:
          ansible_host: 192.168.10.25
      vars:
        ansible_user: root
        ansible_ssh_private_key_file: ~/.ssh/ansible
        ansible_ssh_common_args: "-o StrictHostKeyChecking=no"
    proxmox:
      hosts:
        nova:
          ansible_host: 192.168.10.22
        helix:
          ansible_host: 192.168.10.20
        vega:
          ansible_host: 192.168.10.21
        orion:
          ansible_host: 192.168.10.25
      vars:
        ansible_user: root
    k3s_servers:
      hosts: {}
    k3s_agents:
      hosts: {}
    netboot:
      hosts:
        netboot:
          ansible_host: 192.168.10.156
      vars:
        ansible_user: ansible
        ansible_ssh_private_key_file: ~/.ssh/ansible
        ansible_ssh_common_args: "-o StrictHostKeyChecking=no"
    dev:
      hosts:
        dev:
          ansible_host: 192.168.10.50
      vars:
        ansible_user: ansible
        ansible_ssh_private_key_file: ~/.ssh/ansible
        ansible_ssh_common_args: "-o StrictHostKeyChecking=no"
    vms:
      children:
        k3s_servers: {}
        k3s_agents: {}
        dev: {}
