---
- name: Configure mediastack VM
  hosts: mediastack
  become: true
  vars_files:
    - playbooks/mediastack/vars/mediastack.yml
  roles:
    - base
    - docker
  tasks:
    - import_tasks: playbooks/mediastack/tasks/mediastack.yml
